### ISSUE TITLE
Merlin error when opening .ml file

### ISSUE THREAD

**Issue by johnridesabike** [jordwalke/VimBox#70]
Steps to reproduce:

```
git clone https://github.com/esy-ocaml/hello-reason.git
cd hello-reason
touch lib/A.ml
esy mvim lib/A.ml
```

Output:
```
"lib/A.ml" 0L, 0C
(merlin) backtrace:
Error detected while processing function merlin#Register[117]..merlin#LoadProject:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/x/code/VimBox/dotVim/bundle/vim-reason/autoload/merlin.py", line 740, in setup_merlin
    failures = command("project","get")
  File "/Users/x/code/VimBox/dotVim/bundle/vim-reason/autoload/merlin.py", line 201, in command
    return merlin_process().command(context(cmd))
  File "/Users/x/code/VimBox/dotVim/bundle/vim-reason/autoload/merlin.py", line 170, in command
    raise MerlinException(value)
merlin.MerlinException: 'File "src/kernel/mocaml.ml", line 29, characters 2-8: Assertion failed'
Press ENTER or type command to continue
```

I'm not sure if the error is with VimBox specifically.

**Comment by jordwalke** [comment]
can you say more about what you're using? Are you using the new [json branch](https://github.com/jordwalke/VimBox/tree/json) of vimbox? What plugin are you using for reason (vim-reasonml?)

**Comment by johnridesabike** [comment]
I'm using the master branch. I didn't configure Vim outside of installing VimBox (I backed up my old Vim config and started fresh), so it looks like it's using `chenglou/vim-reason`.

But I think you may have led me to how to fix it. I commented-out `Plug 'chenglou/vim-reason'` and replaced it with `Plug 'jordwalke/vim-reasonml'`. It *seems* to be working okay now.
